// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8007' | (string & {});
};

/**
 * AdmissionCreate
 */
export type AdmissionCreate = {
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    /**
     * Nivel Solicitado
     */
    nivel_solicitado?: string | null;
};

/**
 * AdmissionDetail
 */
export type AdmissionDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    /**
     * Nivel Solicitado
     */
    nivel_solicitado: string | null;
    status: AdmissionStatus;
    /**
     * Current Step
     */
    current_step: number;
    /**
     * Form Data
     */
    form_data: {
        [key: string]: unknown;
    };
    /**
     * Pdf Url
     */
    pdf_url: string | null;
    /**
     * Submitted At
     */
    submitted_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Documents
     */
    documents?: Array<DocumentOut>;
};

/**
 * AdmissionListResponse
 */
export type AdmissionListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Items
     */
    items: Array<AdmissionOut>;
};

/**
 * AdmissionOut
 */
export type AdmissionOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    /**
     * Nivel Solicitado
     */
    nivel_solicitado: string | null;
    status: AdmissionStatus;
    /**
     * Current Step
     */
    current_step: number;
    /**
     * Form Data
     */
    form_data: {
        [key: string]: unknown;
    };
    /**
     * Pdf Url
     */
    pdf_url: string | null;
    /**
     * Submitted At
     */
    submitted_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * AdmissionStatus
 *
 * Máquina de estados de la solicitud de admisión.
 *
 * Transiciones válidas:
 * draft → submitted
 * submitted → reviewing
 * reviewing → documents_pending | approved | rejected
 * documents_pending → documents_complete
 * documents_complete → approved | rejected
 * approved → enrolled | withdrawn
 * rejected → (terminal)
 * withdrawn → (terminal)
 * enrolled → (terminal)
 */
export type AdmissionStatus = 'draft' | 'submitted' | 'reviewing' | 'documents_pending' | 'documents_complete' | 'approved' | 'rejected' | 'enrolled' | 'withdrawn';

/**
 * AdmissionTransition
 */
export type AdmissionTransition = {
    new_status: AdmissionStatus;
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * AdmissionUpdate
 *
 * Actualización parcial de form_data (autosave por paso).
 */
export type AdmissionUpdate = {
    /**
     * Current Step
     */
    current_step?: number | null;
    /**
     * Form Data
     */
    form_data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Notes Internal
     */
    notes_internal?: string | null;
};

/**
 * AlumnoCreate
 */
export type AlumnoCreate = {
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Apellidos
     */
    apellidos: string;
    /**
     * Fecha Nacimiento
     */
    fecha_nacimiento?: string | null;
    /**
     * Genero
     */
    genero?: string | null;
    /**
     * Nacionalidad
     */
    nacionalidad?: string | null;
    /**
     * Nivel
     */
    nivel?: string | null;
    /**
     * Aula
     */
    aula?: string | null;
    /**
     * Tutores
     */
    tutores?: Array<TutorCreate>;
    datos_medicos?: DatosMedicosPayload | null;
};

/**
 * AlumnoDetail
 */
export type AlumnoDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Apellidos
     */
    apellidos: string;
    /**
     * Nombre Completo
     */
    nombre_completo: string;
    /**
     * Fecha Nacimiento
     */
    fecha_nacimiento: string | null;
    /**
     * Nivel
     */
    nivel: string | null;
    /**
     * Aula
     */
    aula: string | null;
    status: AlumnoStatus;
    consentimiento_foto: ConsentimientoFoto;
    /**
     * Consentimiento Datos
     */
    consentimiento_datos: boolean;
    /**
     * Foto Url
     */
    foto_url: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Tutores
     */
    tutores?: Array<TutorOut>;
    datos_medicos?: DatosMedicosPayload | null;
};

/**
 * AlumnoListResponse
 */
export type AlumnoListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Items
     */
    items: Array<AlumnoOut>;
};

/**
 * AlumnoOut
 */
export type AlumnoOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Apellidos
     */
    apellidos: string;
    /**
     * Nombre Completo
     */
    nombre_completo: string;
    /**
     * Fecha Nacimiento
     */
    fecha_nacimiento: string | null;
    /**
     * Nivel
     */
    nivel: string | null;
    /**
     * Aula
     */
    aula: string | null;
    status: AlumnoStatus;
    consentimiento_foto: ConsentimientoFoto;
    /**
     * Consentimiento Datos
     */
    consentimiento_datos: boolean;
    /**
     * Foto Url
     */
    foto_url: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * AlumnoStatus
 */
export type AlumnoStatus = 'inquiry' | 'prospect' | 'admitted' | 'enrolled' | 'waitlisted' | 'withdrawn' | 'graduated';

/**
 * AlumnoUpdate
 */
export type AlumnoUpdate = {
    /**
     * Nombre
     */
    nombre?: string | null;
    /**
     * Apellidos
     */
    apellidos?: string | null;
    /**
     * Fecha Nacimiento
     */
    fecha_nacimiento?: string | null;
    /**
     * Genero
     */
    genero?: string | null;
    /**
     * Nivel
     */
    nivel?: string | null;
    /**
     * Aula
     */
    aula?: string | null;
    status?: AlumnoStatus | null;
    consentimiento_foto?: ConsentimientoFoto | null;
    /**
     * Consentimiento Datos
     */
    consentimiento_datos?: boolean | null;
};

/**
 * AsistenciaEstado
 */
export type AsistenciaEstado = 'presente' | 'ausente' | 'tarde' | 'justificado';

/**
 * AsistenciaListResponse
 */
export type AsistenciaListResponse = {
    /**
     * Data
     */
    data: Array<AsistenciaOut>;
    /**
     * Total
     */
    total: number;
};

/**
 * AsistenciaOut
 */
export type AsistenciaOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Fecha
     */
    fecha: string;
    estado: AsistenciaEstado;
    /**
     * Nota
     */
    nota: string | null;
    /**
     * Justificado Por
     */
    justificado_por: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * AsistenciaUpsert
 */
export type AsistenciaUpsert = {
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Fecha
     */
    fecha: string;
    estado: AsistenciaEstado;
    /**
     * Nota
     */
    nota?: string | null;
};

/**
 * CampaignCreate
 */
export type CampaignCreate = {
    /**
     * Template Id
     */
    template_id: string;
    /**
     * Name
     */
    name: string;
    segment: SegmentFilter;
    /**
     * Scheduled At
     */
    scheduled_at?: string | null;
};

/**
 * CampaignListResponse
 */
export type CampaignListResponse = {
    /**
     * Data
     */
    data: Array<CampaignOut>;
    /**
     * Total
     */
    total: number;
};

/**
 * CampaignOut
 */
export type CampaignOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Template Id
     */
    template_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Segment
     */
    segment: {
        [key: string]: unknown;
    };
    status: CampaignStatus;
    /**
     * Scheduled At
     */
    scheduled_at: string | null;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Total
     */
    total: number;
    /**
     * Sent
     */
    sent: number;
    /**
     * Failed
     */
    failed: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CampaignStatus
 */
export type CampaignStatus = 'draft' | 'scheduled' | 'sending' | 'done' | 'failed';

/**
 * Channel
 */
export type Channel = 'email' | 'whatsapp' | 'inapp';

/**
 * ConsentimientoFoto
 */
export type ConsentimientoFoto = 'si' | 'no' | 'pendiente';

/**
 * CuotaListResponse
 */
export type CuotaListResponse = {
    /**
     * Data
     */
    data: Array<CuotaOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Pendiente Total
     */
    pendiente_total: string;
    /**
     * Cobrada Total
     */
    cobrada_total: string;
};

/**
 * CuotaMarkPaid
 */
export type CuotaMarkPaid = {
    tipo: PagoTipo;
    /**
     * Fecha
     */
    fecha: string;
    /**
     * Referencia Externa
     */
    referencia_externa?: string | null;
    /**
     * Nota
     */
    nota?: string | null;
};

/**
 * CuotaOut
 */
export type CuotaOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Plan Pago Id
     */
    plan_pago_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Periodo
     */
    periodo: string;
    /**
     * Vencimiento
     */
    vencimiento: string;
    /**
     * Importe Base
     */
    importe_base: string;
    /**
     * Descuento Pct
     */
    descuento_pct: string;
    /**
     * Importe Final
     */
    importe_final: string;
    /**
     * Concepto
     */
    concepto: string;
    status: CuotaStatus;
    /**
     * Stripe Payment Intent Id
     */
    stripe_payment_intent_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CuotaStatus
 */
export type CuotaStatus = 'pendiente' | 'en_remesa' | 'cobrada' | 'devuelta' | 'anulada' | 'pagada_manual';

/**
 * DatosMedicosPayload
 *
 * Payload claro — nunca se persiste directamente, se cifra antes.
 */
export type DatosMedicosPayload = {
    /**
     * Alergias
     */
    alergias?: Array<string>;
    /**
     * Medicacion
     */
    medicacion?: Array<string>;
    /**
     * Condiciones
     */
    condiciones?: Array<string>;
    /**
     * Grupo Sanguineo
     */
    grupo_sanguineo?: string | null;
    /**
     * Medico Nombre
     */
    medico_nombre?: string | null;
    /**
     * Medico Tel
     */
    medico_tel?: string | null;
    /**
     * Notas
     */
    notas?: string | null;
};

/**
 * DevolucionCreate
 */
export type DevolucionCreate = {
    /**
     * Cuota Id
     */
    cuota_id: string;
    motivo: DevolucionMotivo;
    /**
     * Fecha
     */
    fecha: string;
    /**
     * Nota
     */
    nota?: string | null;
};

/**
 * DevolucionMotivo
 */
export type DevolucionMotivo = 'fondos_insuficientes' | 'cuenta_cancelada' | 'mandato_revocado' | 'datos_incorrectos' | 'otro';

/**
 * DevolucionOut
 */
export type DevolucionOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Cuota Id
     */
    cuota_id: string;
    motivo: DevolucionMotivo;
    /**
     * Fecha
     */
    fecha: string;
    /**
     * Importe
     */
    importe: string;
    /**
     * Nota
     */
    nota: string | null;
    /**
     * Resuelta
     */
    resuelta: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DevolucionResolve
 */
export type DevolucionResolve = {
    /**
     * Nota
     */
    nota?: string | null;
};

/**
 * DocumentOut
 */
export type DocumentOut = {
    /**
     * Id
     */
    id: string;
    doc_type: DocumentType;
    status: DocumentStatus;
    /**
     * File Url
     */
    file_url: string | null;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Required
     */
    required: boolean;
    /**
     * Uploaded At
     */
    uploaded_at: string | null;
};

/**
 * DocumentStatus
 */
export type DocumentStatus = 'pending' | 'uploaded' | 'approved' | 'rejected';

/**
 * DocumentType
 */
export type DocumentType = 'dni_tutor' | 'libro_familia' | 'partida_nacimiento' | 'cartilla_vacunacion' | 'informe_medico' | 'foto_alumno' | 'contrato_firmado' | 'sepa_mandato';

/**
 * DocumentUpload
 */
export type DocumentUpload = {
    doc_type: DocumentType;
    /**
     * File Url
     */
    file_url: string;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * FinancialSummary
 */
export type FinancialSummary = {
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    /**
     * Cuotas Pendientes
     */
    cuotas_pendientes: number;
    /**
     * Importe Pendiente
     */
    importe_pendiente: string;
    /**
     * Cuotas Cobradas
     */
    cuotas_cobradas: number;
    /**
     * Importe Cobrado
     */
    importe_cobrado: string;
    /**
     * Cuotas Devueltas
     */
    cuotas_devueltas: number;
    /**
     * Importe Devuelto
     */
    importe_devuelto: string;
    /**
     * Remesas Total
     */
    remesas_total: number;
};

/**
 * FotoCreate
 */
export type FotoCreate = {
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Fecha
     */
    fecha: string;
    /**
     * Url Minio
     */
    url_minio: string;
};

/**
 * FotoOut
 */
export type FotoOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Fecha
     */
    fecha: string;
    /**
     * Url Minio
     */
    url_minio: string;
    /**
     * Aprobada
     */
    aprobada: boolean;
    /**
     * Consentimiento Ok
     */
    consentimiento_ok: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InformeCreate
 */
export type InformeCreate = {
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    /**
     * Trimestre
     */
    trimestre: number;
};

/**
 * InformeOut
 */
export type InformeOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    /**
     * Trimestre
     */
    trimestre: number;
    /**
     * Docx Minio Path
     */
    docx_minio_path: string | null;
    /**
     * Generado En
     */
    generado_en: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Tenant Slug
     */
    tenant_slug: string;
};

/**
 * MandatoSepaCreate
 */
export type MandatoSepaCreate = {
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Titular
     */
    titular: string;
    /**
     * Iban
     */
    iban: string;
    /**
     * Bic
     */
    bic?: string | null;
    /**
     * Firmado El
     */
    firmado_el?: string | null;
};

/**
 * MandatoSepaOut
 */
export type MandatoSepaOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Referencia
     */
    referencia: string;
    /**
     * Titular
     */
    titular: string;
    /**
     * Iban Last4
     */
    iban_last4: string;
    /**
     * Bic
     */
    bic: string | null;
    /**
     * Firmado El
     */
    firmado_el: string | null;
    /**
     * Activo
     */
    activo: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MeResponse
 */
export type MeResponse = {
    user: UserOut;
    tenant: TenantOut;
    role: UserRole;
};

/**
 * MessageListResponse
 */
export type MessageListResponse = {
    /**
     * Data
     */
    data: Array<MessageOut>;
    /**
     * Total
     */
    total: number;
};

/**
 * MessageOut
 */
export type MessageOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Campaign Id
     */
    campaign_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    channel: Channel;
    status: MessageStatus;
    /**
     * Recipient
     */
    recipient: string | null;
    /**
     * Sent At
     */
    sent_at: string | null;
    /**
     * Error
     */
    error: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MessageStatus
 */
export type MessageStatus = 'pending' | 'sent' | 'failed' | 'bounced';

/**
 * NivelObservacion
 */
export type NivelObservacion = 'bajo' | 'medio' | 'alto';

/**
 * NpsSummary
 */
export type NpsSummary = {
    /**
     * Total
     */
    total: number;
    /**
     * Promedio
     */
    promedio: number;
    /**
     * Promotores
     */
    promotores: number;
    /**
     * Detractores
     */
    detractores: number;
    /**
     * Nps Score
     */
    nps_score: number;
};

/**
 * ObservacionCreate
 */
export type ObservacionCreate = {
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Fecha
     */
    fecha: string;
    motora?: NivelObservacion | null;
    lenguaje?: NivelObservacion | null;
    social?: NivelObservacion | null;
    emocional?: NivelObservacion | null;
    cognitiva?: NivelObservacion | null;
    /**
     * Comentario
     */
    comentario?: string | null;
};

/**
 * ObservacionOut
 */
export type ObservacionOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Fecha
     */
    fecha: string;
    /**
     * Autor Id
     */
    autor_id: string;
    motora: NivelObservacion | null;
    lenguaje: NivelObservacion | null;
    social: NivelObservacion | null;
    emocional: NivelObservacion | null;
    cognitiva: NivelObservacion | null;
    /**
     * Comentario
     */
    comentario: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PagoTipo
 */
export type PagoTipo = 'efectivo' | 'transferencia' | 'stripe' | 'otro';

/**
 * ParentescoType
 */
export type ParentescoType = 'padre' | 'madre' | 'tutor_legal' | 'abuelo' | 'abuela' | 'otro';

/**
 * PasswordForgotRequest
 */
export type PasswordForgotRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Tenant Slug
     */
    tenant_slug: string;
};

/**
 * PasswordResetRequest
 */
export type PasswordResetRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * Periodicidad
 */
export type Periodicidad = 'mensual' | 'trimestral' | 'anual';

/**
 * PlanPagoCreate
 */
export type PlanPagoCreate = {
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Tarifa Id
     */
    tarifa_id: string;
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    periodicidad: Periodicidad;
    /**
     * Descuento Extra Pct
     */
    descuento_extra_pct?: number | string;
    /**
     * Mandato Sepa Id
     */
    mandato_sepa_id?: string | null;
};

/**
 * PlanPagoWithCuotas
 */
export type PlanPagoWithCuotas = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    /**
     * Tarifa Id
     */
    tarifa_id: string;
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    periodicidad: Periodicidad;
    /**
     * Descuento Extra Pct
     */
    descuento_extra_pct: string;
    /**
     * Mandato Sepa Id
     */
    mandato_sepa_id: string | null;
    /**
     * Activo
     */
    activo: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Cuotas
     */
    cuotas?: Array<CuotaOut>;
};

/**
 * PreferenceOut
 */
export type PreferenceOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Alumno Id
     */
    alumno_id: string;
    channel: Channel;
    /**
     * Opt In
     */
    opt_in: boolean;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PreferenceUpsert
 */
export type PreferenceUpsert = {
    channel: Channel;
    /**
     * Opt In
     */
    opt_in: boolean;
};

/**
 * ReciboListResponse
 */
export type ReciboListResponse = {
    /**
     * Data
     */
    data: Array<ReciboOut>;
    /**
     * Total
     */
    total: number;
};

/**
 * ReciboOut
 */
export type ReciboOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Cuota Id
     */
    cuota_id: string;
    /**
     * Numero
     */
    numero: string;
    /**
     * Importe
     */
    importe: string;
    /**
     * Fecha Emision
     */
    fecha_emision: string;
    /**
     * Pdf Url
     */
    pdf_url: string | null;
    /**
     * Sha256
     */
    sha256: string | null;
    pago_tipo: PagoTipo;
    /**
     * Stripe Charge Id
     */
    stripe_charge_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RemesaListResponse
 */
export type RemesaListResponse = {
    /**
     * Data
     */
    data: Array<RemesaSepaOut>;
    /**
     * Total
     */
    total: number;
};

/**
 * RemesaSepaCreate
 */
export type RemesaSepaCreate = {
    /**
     * Periodo
     */
    periodo: string;
    /**
     * Fecha Cobro
     */
    fecha_cobro: string;
    /**
     * Cuota Ids
     */
    cuota_ids: Array<string>;
    /**
     * Creditor Iban
     */
    creditor_iban: string;
    /**
     * Creditor Name
     */
    creditor_name: string;
    /**
     * Creditor Id
     */
    creditor_id: string;
};

/**
 * RemesaSepaOut
 */
export type RemesaSepaOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Referencia
     */
    referencia: string;
    /**
     * Periodo
     */
    periodo: string;
    /**
     * Fecha Cobro
     */
    fecha_cobro: string;
    /**
     * Importe Total
     */
    importe_total: string;
    /**
     * Num Cuotas
     */
    num_cuotas: number;
    status: RemesaStatus;
    /**
     * Xml Url
     */
    xml_url: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RemesaStatus
 */
export type RemesaStatus = 'borrador' | 'enviada' | 'procesada' | 'parcialmente_devuelta';

/**
 * SegmentFilter
 */
export type SegmentFilter = {
    /**
     * Type
     */
    type: 'all' | 'grade' | 'custom';
    /**
     * Levels
     */
    levels?: Array<string> | null;
    /**
     * Alumno Ids
     */
    alumno_ids?: Array<string> | null;
};

/**
 * SendCampaignRequest
 */
export type SendCampaignRequest = {
    /**
     * Send Now
     */
    send_now?: boolean;
};

/**
 * StripePaymentIntentOut
 */
export type StripePaymentIntentOut = {
    /**
     * Cuota Id
     */
    cuota_id: string;
    /**
     * Client Secret
     */
    client_secret: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Currency
     */
    currency: string;
};

/**
 * TarifaCreate
 */
export type TarifaCreate = {
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Nivel
     */
    nivel: string;
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    /**
     * Importe Mensual
     */
    importe_mensual: number | string;
    /**
     * Descuento Anual Pct
     */
    descuento_anual_pct?: number | string;
    /**
     * Conceptos Extra
     */
    conceptos_extra?: {
        [key: string]: unknown;
    };
    /**
     * Activa
     */
    activa?: boolean;
};

/**
 * TarifaListResponse
 */
export type TarifaListResponse = {
    /**
     * Data
     */
    data: Array<TarifaOut>;
    /**
     * Total
     */
    total: number;
};

/**
 * TarifaOut
 */
export type TarifaOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Nivel
     */
    nivel: string;
    /**
     * Anio Escolar
     */
    anio_escolar: string;
    /**
     * Importe Mensual
     */
    importe_mensual: string;
    /**
     * Descuento Anual Pct
     */
    descuento_anual_pct: string;
    /**
     * Conceptos Extra
     */
    conceptos_extra: {
        [key: string]: unknown;
    };
    /**
     * Activa
     */
    activa: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TemplateCreate
 */
export type TemplateCreate = {
    /**
     * Name
     */
    name: string;
    channel: Channel;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Html Body
     */
    html_body: string;
    /**
     * Text Body
     */
    text_body?: string | null;
};

/**
 * TemplateListResponse
 */
export type TemplateListResponse = {
    /**
     * Data
     */
    data: Array<TemplateOut>;
    /**
     * Total
     */
    total: number;
};

/**
 * TemplateOut
 */
export type TemplateOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Name
     */
    name: string;
    channel: Channel;
    /**
     * Subject
     */
    subject: string | null;
    /**
     * Html Body
     */
    html_body: string;
    /**
     * Text Body
     */
    text_body: string | null;
    /**
     * Active
     */
    active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TenantCreate
 */
export type TenantCreate = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
};

/**
 * TenantOut
 */
export type TenantOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    status: TenantStatus;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TenantStatus
 */
export type TenantStatus = 'active' | 'suspended' | 'trial';

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Expires In
     */
    expires_in: number;
};

/**
 * TutorCreate
 */
export type TutorCreate = {
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Apellidos
     */
    apellidos: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Telefono
     */
    telefono?: string | null;
    /**
     * Telefono Alt
     */
    telefono_alt?: string | null;
    /**
     * Dni
     */
    dni?: string | null;
    parentesco: ParentescoType;
    /**
     * Es Responsable Principal
     */
    es_responsable_principal?: boolean;
    /**
     * Autorizado Recoger
     */
    autorizado_recoger?: boolean;
};

/**
 * TutorOut
 */
export type TutorOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Apellidos
     */
    apellidos: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Telefono
     */
    telefono: string | null;
    parentesco: ParentescoType;
    /**
     * Es Responsable Principal
     */
    es_responsable_principal: boolean;
    /**
     * Autorizado Recoger
     */
    autorizado_recoger: boolean;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    role?: UserRole;
    /**
     * Tenant Slug
     */
    tenant_slug: string;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string;
    status: UserStatus;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserRole
 */
export type UserRole = 'superadmin' | 'admin' | 'secretary' | 'teacher' | 'family' | 'auditor';

/**
 * UserStatus
 */
export type UserStatus = 'active' | 'inactive' | 'pending';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type MetricsMetricsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics';
};

export type MetricsMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthzHealthzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzHealthzGetResponses = {
    /**
     * Response Healthz Healthz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthzHealthzGetResponse = HealthzHealthzGetResponses[keyof HealthzHealthzGetResponses];

export type ReadyzReadyzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzReadyzGetResponses = {
    /**
     * Response Readyz Readyz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadyzReadyzGetResponse = ReadyzReadyzGetResponses[keyof ReadyzReadyzGetResponses];

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type RefreshApiV1AuthRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RefreshApiV1AuthRefreshPostResponse = RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type MeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type MeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type MeApiV1AuthMeGetResponse = MeApiV1AuthMeGetResponses[keyof MeApiV1AuthMeGetResponses];

export type ForgotPasswordApiV1AuthForgotPasswordPostData = {
    body: PasswordForgotRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password';
};

export type ForgotPasswordApiV1AuthForgotPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForgotPasswordApiV1AuthForgotPasswordPostError = ForgotPasswordApiV1AuthForgotPasswordPostErrors[keyof ForgotPasswordApiV1AuthForgotPasswordPostErrors];

export type ForgotPasswordApiV1AuthForgotPasswordPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ResetPasswordApiV1AuthResetPasswordPostData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type ResetPasswordApiV1AuthResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordApiV1AuthResetPasswordPostError = ResetPasswordApiV1AuthResetPasswordPostErrors[keyof ResetPasswordApiV1AuthResetPasswordPostErrors];

export type ResetPasswordApiV1AuthResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResetPasswordApiV1AuthResetPasswordPostResponse = ResetPasswordApiV1AuthResetPasswordPostResponses[keyof ResetPasswordApiV1AuthResetPasswordPostResponses];

export type CreateTenantApiV1TenantsPostData = {
    body: TenantCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tenants';
};

export type CreateTenantApiV1TenantsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTenantApiV1TenantsPostError = CreateTenantApiV1TenantsPostErrors[keyof CreateTenantApiV1TenantsPostErrors];

export type CreateTenantApiV1TenantsPostResponses = {
    /**
     * Successful Response
     */
    201: TenantOut;
};

export type CreateTenantApiV1TenantsPostResponse = CreateTenantApiV1TenantsPostResponses[keyof CreateTenantApiV1TenantsPostResponses];

export type CreateUserApiV1UsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type CreateUserApiV1UsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError = CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserOut;
};

export type CreateUserApiV1UsersPostResponse = CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type ListAlumnosApiV1AlumnosGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Status
         */
        status?: AlumnoStatus | null;
    };
    url: '/api/v1/alumnos';
};

export type ListAlumnosApiV1AlumnosGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAlumnosApiV1AlumnosGetError = ListAlumnosApiV1AlumnosGetErrors[keyof ListAlumnosApiV1AlumnosGetErrors];

export type ListAlumnosApiV1AlumnosGetResponses = {
    /**
     * Successful Response
     */
    200: AlumnoListResponse;
};

export type ListAlumnosApiV1AlumnosGetResponse = ListAlumnosApiV1AlumnosGetResponses[keyof ListAlumnosApiV1AlumnosGetResponses];

export type CreateAlumnoApiV1AlumnosPostData = {
    body: AlumnoCreate;
    path?: never;
    query?: never;
    url: '/api/v1/alumnos';
};

export type CreateAlumnoApiV1AlumnosPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAlumnoApiV1AlumnosPostError = CreateAlumnoApiV1AlumnosPostErrors[keyof CreateAlumnoApiV1AlumnosPostErrors];

export type CreateAlumnoApiV1AlumnosPostResponses = {
    /**
     * Successful Response
     */
    201: AlumnoDetail;
};

export type CreateAlumnoApiV1AlumnosPostResponse = CreateAlumnoApiV1AlumnosPostResponses[keyof CreateAlumnoApiV1AlumnosPostResponses];

export type DeleteAlumnoApiV1AlumnosAlumnoIdDeleteData = {
    body?: never;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query?: never;
    url: '/api/v1/alumnos/{alumno_id}';
};

export type DeleteAlumnoApiV1AlumnosAlumnoIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAlumnoApiV1AlumnosAlumnoIdDeleteError = DeleteAlumnoApiV1AlumnosAlumnoIdDeleteErrors[keyof DeleteAlumnoApiV1AlumnosAlumnoIdDeleteErrors];

export type DeleteAlumnoApiV1AlumnosAlumnoIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAlumnoApiV1AlumnosAlumnoIdDeleteResponse = DeleteAlumnoApiV1AlumnosAlumnoIdDeleteResponses[keyof DeleteAlumnoApiV1AlumnosAlumnoIdDeleteResponses];

export type GetAlumnoApiV1AlumnosAlumnoIdGetData = {
    body?: never;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query?: never;
    url: '/api/v1/alumnos/{alumno_id}';
};

export type GetAlumnoApiV1AlumnosAlumnoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAlumnoApiV1AlumnosAlumnoIdGetError = GetAlumnoApiV1AlumnosAlumnoIdGetErrors[keyof GetAlumnoApiV1AlumnosAlumnoIdGetErrors];

export type GetAlumnoApiV1AlumnosAlumnoIdGetResponses = {
    /**
     * Successful Response
     */
    200: AlumnoDetail;
};

export type GetAlumnoApiV1AlumnosAlumnoIdGetResponse = GetAlumnoApiV1AlumnosAlumnoIdGetResponses[keyof GetAlumnoApiV1AlumnosAlumnoIdGetResponses];

export type UpdateAlumnoApiV1AlumnosAlumnoIdPatchData = {
    body: AlumnoUpdate;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query?: never;
    url: '/api/v1/alumnos/{alumno_id}';
};

export type UpdateAlumnoApiV1AlumnosAlumnoIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAlumnoApiV1AlumnosAlumnoIdPatchError = UpdateAlumnoApiV1AlumnosAlumnoIdPatchErrors[keyof UpdateAlumnoApiV1AlumnosAlumnoIdPatchErrors];

export type UpdateAlumnoApiV1AlumnosAlumnoIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AlumnoDetail;
};

export type UpdateAlumnoApiV1AlumnosAlumnoIdPatchResponse = UpdateAlumnoApiV1AlumnosAlumnoIdPatchResponses[keyof UpdateAlumnoApiV1AlumnosAlumnoIdPatchResponses];

export type GetDatosMedicosApiV1AlumnosAlumnoIdMedicoGetData = {
    body?: never;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query?: never;
    url: '/api/v1/alumnos/{alumno_id}/medico';
};

export type GetDatosMedicosApiV1AlumnosAlumnoIdMedicoGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDatosMedicosApiV1AlumnosAlumnoIdMedicoGetError = GetDatosMedicosApiV1AlumnosAlumnoIdMedicoGetErrors[keyof GetDatosMedicosApiV1AlumnosAlumnoIdMedicoGetErrors];

export type GetDatosMedicosApiV1AlumnosAlumnoIdMedicoGetResponses = {
    /**
     * Successful Response
     */
    200: DatosMedicosPayload;
};

export type GetDatosMedicosApiV1AlumnosAlumnoIdMedicoGetResponse = GetDatosMedicosApiV1AlumnosAlumnoIdMedicoGetResponses[keyof GetDatosMedicosApiV1AlumnosAlumnoIdMedicoGetResponses];

export type UpdateDatosMedicosApiV1AlumnosAlumnoIdMedicoPutData = {
    body: DatosMedicosPayload;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query?: never;
    url: '/api/v1/alumnos/{alumno_id}/medico';
};

export type UpdateDatosMedicosApiV1AlumnosAlumnoIdMedicoPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDatosMedicosApiV1AlumnosAlumnoIdMedicoPutError = UpdateDatosMedicosApiV1AlumnosAlumnoIdMedicoPutErrors[keyof UpdateDatosMedicosApiV1AlumnosAlumnoIdMedicoPutErrors];

export type UpdateDatosMedicosApiV1AlumnosAlumnoIdMedicoPutResponses = {
    /**
     * Successful Response
     */
    200: DatosMedicosPayload;
};

export type UpdateDatosMedicosApiV1AlumnosAlumnoIdMedicoPutResponse = UpdateDatosMedicosApiV1AlumnosAlumnoIdMedicoPutResponses[keyof UpdateDatosMedicosApiV1AlumnosAlumnoIdMedicoPutResponses];

export type ListAdmissionsApiV1AdmissionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: AdmissionStatus | null;
    };
    url: '/api/v1/admissions';
};

export type ListAdmissionsApiV1AdmissionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAdmissionsApiV1AdmissionsGetError = ListAdmissionsApiV1AdmissionsGetErrors[keyof ListAdmissionsApiV1AdmissionsGetErrors];

export type ListAdmissionsApiV1AdmissionsGetResponses = {
    /**
     * Successful Response
     */
    200: AdmissionListResponse;
};

export type ListAdmissionsApiV1AdmissionsGetResponse = ListAdmissionsApiV1AdmissionsGetResponses[keyof ListAdmissionsApiV1AdmissionsGetResponses];

export type CreateAdmissionApiV1AdmissionsPostData = {
    body: AdmissionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admissions';
};

export type CreateAdmissionApiV1AdmissionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAdmissionApiV1AdmissionsPostError = CreateAdmissionApiV1AdmissionsPostErrors[keyof CreateAdmissionApiV1AdmissionsPostErrors];

export type CreateAdmissionApiV1AdmissionsPostResponses = {
    /**
     * Successful Response
     */
    201: AdmissionDetail;
};

export type CreateAdmissionApiV1AdmissionsPostResponse = CreateAdmissionApiV1AdmissionsPostResponses[keyof CreateAdmissionApiV1AdmissionsPostResponses];

export type GetAdmissionApiV1AdmissionsAdmissionIdGetData = {
    body?: never;
    path: {
        /**
         * Admission Id
         */
        admission_id: string;
    };
    query?: never;
    url: '/api/v1/admissions/{admission_id}';
};

export type GetAdmissionApiV1AdmissionsAdmissionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAdmissionApiV1AdmissionsAdmissionIdGetError = GetAdmissionApiV1AdmissionsAdmissionIdGetErrors[keyof GetAdmissionApiV1AdmissionsAdmissionIdGetErrors];

export type GetAdmissionApiV1AdmissionsAdmissionIdGetResponses = {
    /**
     * Successful Response
     */
    200: AdmissionDetail;
};

export type GetAdmissionApiV1AdmissionsAdmissionIdGetResponse = GetAdmissionApiV1AdmissionsAdmissionIdGetResponses[keyof GetAdmissionApiV1AdmissionsAdmissionIdGetResponses];

export type UpdateFormApiV1AdmissionsAdmissionIdPatchData = {
    body: AdmissionUpdate;
    path: {
        /**
         * Admission Id
         */
        admission_id: string;
    };
    query?: never;
    url: '/api/v1/admissions/{admission_id}';
};

export type UpdateFormApiV1AdmissionsAdmissionIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateFormApiV1AdmissionsAdmissionIdPatchError = UpdateFormApiV1AdmissionsAdmissionIdPatchErrors[keyof UpdateFormApiV1AdmissionsAdmissionIdPatchErrors];

export type UpdateFormApiV1AdmissionsAdmissionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AdmissionDetail;
};

export type UpdateFormApiV1AdmissionsAdmissionIdPatchResponse = UpdateFormApiV1AdmissionsAdmissionIdPatchResponses[keyof UpdateFormApiV1AdmissionsAdmissionIdPatchResponses];

export type TransitionApiV1AdmissionsAdmissionIdTransitionPostData = {
    body: AdmissionTransition;
    path: {
        /**
         * Admission Id
         */
        admission_id: string;
    };
    query?: never;
    url: '/api/v1/admissions/{admission_id}/transition';
};

export type TransitionApiV1AdmissionsAdmissionIdTransitionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransitionApiV1AdmissionsAdmissionIdTransitionPostError = TransitionApiV1AdmissionsAdmissionIdTransitionPostErrors[keyof TransitionApiV1AdmissionsAdmissionIdTransitionPostErrors];

export type TransitionApiV1AdmissionsAdmissionIdTransitionPostResponses = {
    /**
     * Successful Response
     */
    200: AdmissionDetail;
};

export type TransitionApiV1AdmissionsAdmissionIdTransitionPostResponse = TransitionApiV1AdmissionsAdmissionIdTransitionPostResponses[keyof TransitionApiV1AdmissionsAdmissionIdTransitionPostResponses];

export type UploadDocumentApiV1AdmissionsAdmissionIdDocumentsPostData = {
    body: DocumentUpload;
    path: {
        /**
         * Admission Id
         */
        admission_id: string;
    };
    query?: never;
    url: '/api/v1/admissions/{admission_id}/documents';
};

export type UploadDocumentApiV1AdmissionsAdmissionIdDocumentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentApiV1AdmissionsAdmissionIdDocumentsPostError = UploadDocumentApiV1AdmissionsAdmissionIdDocumentsPostErrors[keyof UploadDocumentApiV1AdmissionsAdmissionIdDocumentsPostErrors];

export type UploadDocumentApiV1AdmissionsAdmissionIdDocumentsPostResponses = {
    /**
     * Successful Response
     */
    200: AdmissionDetail;
};

export type UploadDocumentApiV1AdmissionsAdmissionIdDocumentsPostResponse = UploadDocumentApiV1AdmissionsAdmissionIdDocumentsPostResponses[keyof UploadDocumentApiV1AdmissionsAdmissionIdDocumentsPostResponses];

export type GeneratePdfApiV1AdmissionsAdmissionIdPdfPostData = {
    body?: never;
    path: {
        /**
         * Admission Id
         */
        admission_id: string;
    };
    query?: never;
    url: '/api/v1/admissions/{admission_id}/pdf';
};

export type GeneratePdfApiV1AdmissionsAdmissionIdPdfPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeneratePdfApiV1AdmissionsAdmissionIdPdfPostError = GeneratePdfApiV1AdmissionsAdmissionIdPdfPostErrors[keyof GeneratePdfApiV1AdmissionsAdmissionIdPdfPostErrors];

export type GeneratePdfApiV1AdmissionsAdmissionIdPdfPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTarifasApiV1BillingTarifasGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Anio Escolar
         */
        anio_escolar?: string | null;
    };
    url: '/api/v1/billing/tarifas';
};

export type ListTarifasApiV1BillingTarifasGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTarifasApiV1BillingTarifasGetError = ListTarifasApiV1BillingTarifasGetErrors[keyof ListTarifasApiV1BillingTarifasGetErrors];

export type ListTarifasApiV1BillingTarifasGetResponses = {
    /**
     * Successful Response
     */
    200: TarifaListResponse;
};

export type ListTarifasApiV1BillingTarifasGetResponse = ListTarifasApiV1BillingTarifasGetResponses[keyof ListTarifasApiV1BillingTarifasGetResponses];

export type CreateTarifaApiV1BillingTarifasPostData = {
    body: TarifaCreate;
    path?: never;
    query?: never;
    url: '/api/v1/billing/tarifas';
};

export type CreateTarifaApiV1BillingTarifasPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTarifaApiV1BillingTarifasPostError = CreateTarifaApiV1BillingTarifasPostErrors[keyof CreateTarifaApiV1BillingTarifasPostErrors];

export type CreateTarifaApiV1BillingTarifasPostResponses = {
    /**
     * Successful Response
     */
    201: TarifaOut;
};

export type CreateTarifaApiV1BillingTarifasPostResponse = CreateTarifaApiV1BillingTarifasPostResponses[keyof CreateTarifaApiV1BillingTarifasPostResponses];

export type CreateMandatoApiV1BillingMandatosPostData = {
    body: MandatoSepaCreate;
    path?: never;
    query?: never;
    url: '/api/v1/billing/mandatos';
};

export type CreateMandatoApiV1BillingMandatosPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMandatoApiV1BillingMandatosPostError = CreateMandatoApiV1BillingMandatosPostErrors[keyof CreateMandatoApiV1BillingMandatosPostErrors];

export type CreateMandatoApiV1BillingMandatosPostResponses = {
    /**
     * Successful Response
     */
    201: MandatoSepaOut;
};

export type CreateMandatoApiV1BillingMandatosPostResponse = CreateMandatoApiV1BillingMandatosPostResponses[keyof CreateMandatoApiV1BillingMandatosPostResponses];

export type CreatePlanApiV1BillingPlanesPostData = {
    body: PlanPagoCreate;
    path?: never;
    query?: never;
    url: '/api/v1/billing/planes';
};

export type CreatePlanApiV1BillingPlanesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePlanApiV1BillingPlanesPostError = CreatePlanApiV1BillingPlanesPostErrors[keyof CreatePlanApiV1BillingPlanesPostErrors];

export type CreatePlanApiV1BillingPlanesPostResponses = {
    /**
     * Successful Response
     */
    201: PlanPagoWithCuotas;
};

export type CreatePlanApiV1BillingPlanesPostResponse = CreatePlanApiV1BillingPlanesPostResponses[keyof CreatePlanApiV1BillingPlanesPostResponses];

export type GetPlanApiV1BillingPlanesPlanIdGetData = {
    body?: never;
    path: {
        /**
         * Plan Id
         */
        plan_id: string;
    };
    query?: never;
    url: '/api/v1/billing/planes/{plan_id}';
};

export type GetPlanApiV1BillingPlanesPlanIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlanApiV1BillingPlanesPlanIdGetError = GetPlanApiV1BillingPlanesPlanIdGetErrors[keyof GetPlanApiV1BillingPlanesPlanIdGetErrors];

export type GetPlanApiV1BillingPlanesPlanIdGetResponses = {
    /**
     * Successful Response
     */
    200: PlanPagoWithCuotas;
};

export type GetPlanApiV1BillingPlanesPlanIdGetResponse = GetPlanApiV1BillingPlanesPlanIdGetResponses[keyof GetPlanApiV1BillingPlanesPlanIdGetResponses];

export type ListCuotasApiV1BillingCuotasGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Alumno Id
         */
        alumno_id?: string | null;
        /**
         * Status
         */
        status?: CuotaStatus | null;
        /**
         * Anio Escolar
         */
        anio_escolar?: string | null;
    };
    url: '/api/v1/billing/cuotas';
};

export type ListCuotasApiV1BillingCuotasGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCuotasApiV1BillingCuotasGetError = ListCuotasApiV1BillingCuotasGetErrors[keyof ListCuotasApiV1BillingCuotasGetErrors];

export type ListCuotasApiV1BillingCuotasGetResponses = {
    /**
     * Successful Response
     */
    200: CuotaListResponse;
};

export type ListCuotasApiV1BillingCuotasGetResponse = ListCuotasApiV1BillingCuotasGetResponses[keyof ListCuotasApiV1BillingCuotasGetResponses];

export type MarkCuotaPaidApiV1BillingCuotasCuotaIdPagarPostData = {
    body: CuotaMarkPaid;
    path: {
        /**
         * Cuota Id
         */
        cuota_id: string;
    };
    query?: never;
    url: '/api/v1/billing/cuotas/{cuota_id}/pagar';
};

export type MarkCuotaPaidApiV1BillingCuotasCuotaIdPagarPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkCuotaPaidApiV1BillingCuotasCuotaIdPagarPostError = MarkCuotaPaidApiV1BillingCuotasCuotaIdPagarPostErrors[keyof MarkCuotaPaidApiV1BillingCuotasCuotaIdPagarPostErrors];

export type MarkCuotaPaidApiV1BillingCuotasCuotaIdPagarPostResponses = {
    /**
     * Response Mark Cuota Paid Api V1 Billing Cuotas  Cuota Id  Pagar Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type MarkCuotaPaidApiV1BillingCuotasCuotaIdPagarPostResponse = MarkCuotaPaidApiV1BillingCuotasCuotaIdPagarPostResponses[keyof MarkCuotaPaidApiV1BillingCuotasCuotaIdPagarPostResponses];

export type CreatePaymentIntentApiV1BillingCuotasCuotaIdStripeIntentPostData = {
    body?: never;
    path: {
        /**
         * Cuota Id
         */
        cuota_id: string;
    };
    query?: never;
    url: '/api/v1/billing/cuotas/{cuota_id}/stripe/intent';
};

export type CreatePaymentIntentApiV1BillingCuotasCuotaIdStripeIntentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaymentIntentApiV1BillingCuotasCuotaIdStripeIntentPostError = CreatePaymentIntentApiV1BillingCuotasCuotaIdStripeIntentPostErrors[keyof CreatePaymentIntentApiV1BillingCuotasCuotaIdStripeIntentPostErrors];

export type CreatePaymentIntentApiV1BillingCuotasCuotaIdStripeIntentPostResponses = {
    /**
     * Successful Response
     */
    200: StripePaymentIntentOut;
};

export type CreatePaymentIntentApiV1BillingCuotasCuotaIdStripeIntentPostResponse = CreatePaymentIntentApiV1BillingCuotasCuotaIdStripeIntentPostResponses[keyof CreatePaymentIntentApiV1BillingCuotasCuotaIdStripeIntentPostResponses];

export type ListRemesasApiV1BillingRemesasGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/billing/remesas';
};

export type ListRemesasApiV1BillingRemesasGetResponses = {
    /**
     * Successful Response
     */
    200: RemesaListResponse;
};

export type ListRemesasApiV1BillingRemesasGetResponse = ListRemesasApiV1BillingRemesasGetResponses[keyof ListRemesasApiV1BillingRemesasGetResponses];

export type CreateRemesaApiV1BillingRemesasPostData = {
    body: RemesaSepaCreate;
    path?: never;
    query?: never;
    url: '/api/v1/billing/remesas';
};

export type CreateRemesaApiV1BillingRemesasPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRemesaApiV1BillingRemesasPostError = CreateRemesaApiV1BillingRemesasPostErrors[keyof CreateRemesaApiV1BillingRemesasPostErrors];

export type CreateRemesaApiV1BillingRemesasPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type ConfirmRemesaApiV1BillingRemesasRemesaIdConfirmarPostData = {
    body?: never;
    path: {
        /**
         * Remesa Id
         */
        remesa_id: string;
    };
    query?: never;
    url: '/api/v1/billing/remesas/{remesa_id}/confirmar';
};

export type ConfirmRemesaApiV1BillingRemesasRemesaIdConfirmarPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmRemesaApiV1BillingRemesasRemesaIdConfirmarPostError = ConfirmRemesaApiV1BillingRemesasRemesaIdConfirmarPostErrors[keyof ConfirmRemesaApiV1BillingRemesasRemesaIdConfirmarPostErrors];

export type ConfirmRemesaApiV1BillingRemesasRemesaIdConfirmarPostResponses = {
    /**
     * Successful Response
     */
    200: RemesaSepaOut;
};

export type ConfirmRemesaApiV1BillingRemesasRemesaIdConfirmarPostResponse = ConfirmRemesaApiV1BillingRemesasRemesaIdConfirmarPostResponses[keyof ConfirmRemesaApiV1BillingRemesasRemesaIdConfirmarPostResponses];

export type ListDevolucionesApiV1BillingDevolucionesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Resuelta
         */
        resuelta?: boolean | null;
    };
    url: '/api/v1/billing/devoluciones';
};

export type ListDevolucionesApiV1BillingDevolucionesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDevolucionesApiV1BillingDevolucionesGetError = ListDevolucionesApiV1BillingDevolucionesGetErrors[keyof ListDevolucionesApiV1BillingDevolucionesGetErrors];

export type ListDevolucionesApiV1BillingDevolucionesGetResponses = {
    /**
     * Response List Devoluciones Api V1 Billing Devoluciones Get
     *
     * Successful Response
     */
    200: Array<DevolucionOut>;
};

export type ListDevolucionesApiV1BillingDevolucionesGetResponse = ListDevolucionesApiV1BillingDevolucionesGetResponses[keyof ListDevolucionesApiV1BillingDevolucionesGetResponses];

export type RegisterDevolucionApiV1BillingDevolucionesPostData = {
    body: DevolucionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/billing/devoluciones';
};

export type RegisterDevolucionApiV1BillingDevolucionesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterDevolucionApiV1BillingDevolucionesPostError = RegisterDevolucionApiV1BillingDevolucionesPostErrors[keyof RegisterDevolucionApiV1BillingDevolucionesPostErrors];

export type RegisterDevolucionApiV1BillingDevolucionesPostResponses = {
    /**
     * Successful Response
     */
    201: DevolucionOut;
};

export type RegisterDevolucionApiV1BillingDevolucionesPostResponse = RegisterDevolucionApiV1BillingDevolucionesPostResponses[keyof RegisterDevolucionApiV1BillingDevolucionesPostResponses];

export type ResolveDevolucionApiV1BillingDevolucionesDevolucionIdResolverPatchData = {
    body: DevolucionResolve;
    path: {
        /**
         * Devolucion Id
         */
        devolucion_id: string;
    };
    query?: never;
    url: '/api/v1/billing/devoluciones/{devolucion_id}/resolver';
};

export type ResolveDevolucionApiV1BillingDevolucionesDevolucionIdResolverPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveDevolucionApiV1BillingDevolucionesDevolucionIdResolverPatchError = ResolveDevolucionApiV1BillingDevolucionesDevolucionIdResolverPatchErrors[keyof ResolveDevolucionApiV1BillingDevolucionesDevolucionIdResolverPatchErrors];

export type ResolveDevolucionApiV1BillingDevolucionesDevolucionIdResolverPatchResponses = {
    /**
     * Successful Response
     */
    200: DevolucionOut;
};

export type ResolveDevolucionApiV1BillingDevolucionesDevolucionIdResolverPatchResponse = ResolveDevolucionApiV1BillingDevolucionesDevolucionIdResolverPatchResponses[keyof ResolveDevolucionApiV1BillingDevolucionesDevolucionIdResolverPatchResponses];

export type ListRecibosApiV1BillingRecibosGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Alumno Id
         */
        alumno_id?: string | null;
    };
    url: '/api/v1/billing/recibos';
};

export type ListRecibosApiV1BillingRecibosGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRecibosApiV1BillingRecibosGetError = ListRecibosApiV1BillingRecibosGetErrors[keyof ListRecibosApiV1BillingRecibosGetErrors];

export type ListRecibosApiV1BillingRecibosGetResponses = {
    /**
     * Successful Response
     */
    200: ReciboListResponse;
};

export type ListRecibosApiV1BillingRecibosGetResponse = ListRecibosApiV1BillingRecibosGetResponses[keyof ListRecibosApiV1BillingRecibosGetResponses];

export type FinancialSummaryApiV1BillingSummaryGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Anio Escolar
         */
        anio_escolar: string;
    };
    url: '/api/v1/billing/summary';
};

export type FinancialSummaryApiV1BillingSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FinancialSummaryApiV1BillingSummaryGetError = FinancialSummaryApiV1BillingSummaryGetErrors[keyof FinancialSummaryApiV1BillingSummaryGetErrors];

export type FinancialSummaryApiV1BillingSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: FinancialSummary;
};

export type FinancialSummaryApiV1BillingSummaryGetResponse = FinancialSummaryApiV1BillingSummaryGetResponses[keyof FinancialSummaryApiV1BillingSummaryGetResponses];

export type ListTemplatesApiV1CommunicationsTemplatesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/communications/templates';
};

export type ListTemplatesApiV1CommunicationsTemplatesGetResponses = {
    /**
     * Successful Response
     */
    200: TemplateListResponse;
};

export type ListTemplatesApiV1CommunicationsTemplatesGetResponse = ListTemplatesApiV1CommunicationsTemplatesGetResponses[keyof ListTemplatesApiV1CommunicationsTemplatesGetResponses];

export type CreateTemplateApiV1CommunicationsTemplatesPostData = {
    body: TemplateCreate;
    path?: never;
    query?: never;
    url: '/api/v1/communications/templates';
};

export type CreateTemplateApiV1CommunicationsTemplatesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTemplateApiV1CommunicationsTemplatesPostError = CreateTemplateApiV1CommunicationsTemplatesPostErrors[keyof CreateTemplateApiV1CommunicationsTemplatesPostErrors];

export type CreateTemplateApiV1CommunicationsTemplatesPostResponses = {
    /**
     * Successful Response
     */
    201: TemplateOut;
};

export type CreateTemplateApiV1CommunicationsTemplatesPostResponse = CreateTemplateApiV1CommunicationsTemplatesPostResponses[keyof CreateTemplateApiV1CommunicationsTemplatesPostResponses];

export type GetTemplateApiV1CommunicationsTemplatesTemplateIdGetData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: string;
    };
    query?: never;
    url: '/api/v1/communications/templates/{template_id}';
};

export type GetTemplateApiV1CommunicationsTemplatesTemplateIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTemplateApiV1CommunicationsTemplatesTemplateIdGetError = GetTemplateApiV1CommunicationsTemplatesTemplateIdGetErrors[keyof GetTemplateApiV1CommunicationsTemplatesTemplateIdGetErrors];

export type GetTemplateApiV1CommunicationsTemplatesTemplateIdGetResponses = {
    /**
     * Successful Response
     */
    200: TemplateOut;
};

export type GetTemplateApiV1CommunicationsTemplatesTemplateIdGetResponse = GetTemplateApiV1CommunicationsTemplatesTemplateIdGetResponses[keyof GetTemplateApiV1CommunicationsTemplatesTemplateIdGetResponses];

export type ListCampaignsApiV1CommunicationsCampaignsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/communications/campaigns';
};

export type ListCampaignsApiV1CommunicationsCampaignsGetResponses = {
    /**
     * Successful Response
     */
    200: CampaignListResponse;
};

export type ListCampaignsApiV1CommunicationsCampaignsGetResponse = ListCampaignsApiV1CommunicationsCampaignsGetResponses[keyof ListCampaignsApiV1CommunicationsCampaignsGetResponses];

export type CreateCampaignApiV1CommunicationsCampaignsPostData = {
    body: CampaignCreate;
    path?: never;
    query?: never;
    url: '/api/v1/communications/campaigns';
};

export type CreateCampaignApiV1CommunicationsCampaignsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCampaignApiV1CommunicationsCampaignsPostError = CreateCampaignApiV1CommunicationsCampaignsPostErrors[keyof CreateCampaignApiV1CommunicationsCampaignsPostErrors];

export type CreateCampaignApiV1CommunicationsCampaignsPostResponses = {
    /**
     * Successful Response
     */
    201: CampaignOut;
};

export type CreateCampaignApiV1CommunicationsCampaignsPostResponse = CreateCampaignApiV1CommunicationsCampaignsPostResponses[keyof CreateCampaignApiV1CommunicationsCampaignsPostResponses];

export type GetCampaignApiV1CommunicationsCampaignsCampaignIdGetData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: string;
    };
    query?: never;
    url: '/api/v1/communications/campaigns/{campaign_id}';
};

export type GetCampaignApiV1CommunicationsCampaignsCampaignIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCampaignApiV1CommunicationsCampaignsCampaignIdGetError = GetCampaignApiV1CommunicationsCampaignsCampaignIdGetErrors[keyof GetCampaignApiV1CommunicationsCampaignsCampaignIdGetErrors];

export type GetCampaignApiV1CommunicationsCampaignsCampaignIdGetResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type GetCampaignApiV1CommunicationsCampaignsCampaignIdGetResponse = GetCampaignApiV1CommunicationsCampaignsCampaignIdGetResponses[keyof GetCampaignApiV1CommunicationsCampaignsCampaignIdGetResponses];

export type SendCampaignApiV1CommunicationsCampaignsCampaignIdSendPostData = {
    body: SendCampaignRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: string;
    };
    query?: never;
    url: '/api/v1/communications/campaigns/{campaign_id}/send';
};

export type SendCampaignApiV1CommunicationsCampaignsCampaignIdSendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendCampaignApiV1CommunicationsCampaignsCampaignIdSendPostError = SendCampaignApiV1CommunicationsCampaignsCampaignIdSendPostErrors[keyof SendCampaignApiV1CommunicationsCampaignsCampaignIdSendPostErrors];

export type SendCampaignApiV1CommunicationsCampaignsCampaignIdSendPostResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type SendCampaignApiV1CommunicationsCampaignsCampaignIdSendPostResponse = SendCampaignApiV1CommunicationsCampaignsCampaignIdSendPostResponses[keyof SendCampaignApiV1CommunicationsCampaignsCampaignIdSendPostResponses];

export type ListMessagesApiV1CommunicationsCampaignsCampaignIdMessagesGetData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: string;
    };
    query?: never;
    url: '/api/v1/communications/campaigns/{campaign_id}/messages';
};

export type ListMessagesApiV1CommunicationsCampaignsCampaignIdMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMessagesApiV1CommunicationsCampaignsCampaignIdMessagesGetError = ListMessagesApiV1CommunicationsCampaignsCampaignIdMessagesGetErrors[keyof ListMessagesApiV1CommunicationsCampaignsCampaignIdMessagesGetErrors];

export type ListMessagesApiV1CommunicationsCampaignsCampaignIdMessagesGetResponses = {
    /**
     * Successful Response
     */
    200: MessageListResponse;
};

export type ListMessagesApiV1CommunicationsCampaignsCampaignIdMessagesGetResponse = ListMessagesApiV1CommunicationsCampaignsCampaignIdMessagesGetResponses[keyof ListMessagesApiV1CommunicationsCampaignsCampaignIdMessagesGetResponses];

export type GetPreferencesApiV1CommunicationsPreferencesAlumnoIdGetData = {
    body?: never;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query?: never;
    url: '/api/v1/communications/preferences/{alumno_id}';
};

export type GetPreferencesApiV1CommunicationsPreferencesAlumnoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPreferencesApiV1CommunicationsPreferencesAlumnoIdGetError = GetPreferencesApiV1CommunicationsPreferencesAlumnoIdGetErrors[keyof GetPreferencesApiV1CommunicationsPreferencesAlumnoIdGetErrors];

export type GetPreferencesApiV1CommunicationsPreferencesAlumnoIdGetResponses = {
    /**
     * Response Get Preferences Api V1 Communications Preferences  Alumno Id  Get
     *
     * Successful Response
     */
    200: Array<PreferenceOut>;
};

export type GetPreferencesApiV1CommunicationsPreferencesAlumnoIdGetResponse = GetPreferencesApiV1CommunicationsPreferencesAlumnoIdGetResponses[keyof GetPreferencesApiV1CommunicationsPreferencesAlumnoIdGetResponses];

export type UpsertPreferenceApiV1CommunicationsPreferencesAlumnoIdPutData = {
    body: PreferenceUpsert;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query?: never;
    url: '/api/v1/communications/preferences/{alumno_id}';
};

export type UpsertPreferenceApiV1CommunicationsPreferencesAlumnoIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertPreferenceApiV1CommunicationsPreferencesAlumnoIdPutError = UpsertPreferenceApiV1CommunicationsPreferencesAlumnoIdPutErrors[keyof UpsertPreferenceApiV1CommunicationsPreferencesAlumnoIdPutErrors];

export type UpsertPreferenceApiV1CommunicationsPreferencesAlumnoIdPutResponses = {
    /**
     * Successful Response
     */
    200: PreferenceOut;
};

export type UpsertPreferenceApiV1CommunicationsPreferencesAlumnoIdPutResponse = UpsertPreferenceApiV1CommunicationsPreferencesAlumnoIdPutResponses[keyof UpsertPreferenceApiV1CommunicationsPreferencesAlumnoIdPutResponses];

export type ListAttendanceForDateApiV1AttendanceGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Fecha
         *
         * Fecha de la asistencia (YYYY-MM-DD)
         */
        fecha: string;
    };
    url: '/api/v1/attendance';
};

export type ListAttendanceForDateApiV1AttendanceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAttendanceForDateApiV1AttendanceGetError = ListAttendanceForDateApiV1AttendanceGetErrors[keyof ListAttendanceForDateApiV1AttendanceGetErrors];

export type ListAttendanceForDateApiV1AttendanceGetResponses = {
    /**
     * Successful Response
     */
    200: AsistenciaListResponse;
};

export type ListAttendanceForDateApiV1AttendanceGetResponse = ListAttendanceForDateApiV1AttendanceGetResponses[keyof ListAttendanceForDateApiV1AttendanceGetResponses];

export type UpsertAttendanceApiV1AttendancePutData = {
    body: AsistenciaUpsert;
    path?: never;
    query?: never;
    url: '/api/v1/attendance';
};

export type UpsertAttendanceApiV1AttendancePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertAttendanceApiV1AttendancePutError = UpsertAttendanceApiV1AttendancePutErrors[keyof UpsertAttendanceApiV1AttendancePutErrors];

export type UpsertAttendanceApiV1AttendancePutResponses = {
    /**
     * Successful Response
     */
    200: AsistenciaOut;
};

export type UpsertAttendanceApiV1AttendancePutResponse = UpsertAttendanceApiV1AttendancePutResponses[keyof UpsertAttendanceApiV1AttendancePutResponses];

export type ListAttendanceForAlumnoApiV1AttendanceAlumnoAlumnoIdGetData = {
    body?: never;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query: {
        /**
         * Desde
         *
         * Start date (inclusive)
         */
        desde: string;
        /**
         * Hasta
         *
         * End date (inclusive)
         */
        hasta: string;
    };
    url: '/api/v1/attendance/alumno/{alumno_id}';
};

export type ListAttendanceForAlumnoApiV1AttendanceAlumnoAlumnoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAttendanceForAlumnoApiV1AttendanceAlumnoAlumnoIdGetError = ListAttendanceForAlumnoApiV1AttendanceAlumnoAlumnoIdGetErrors[keyof ListAttendanceForAlumnoApiV1AttendanceAlumnoAlumnoIdGetErrors];

export type ListAttendanceForAlumnoApiV1AttendanceAlumnoAlumnoIdGetResponses = {
    /**
     * Successful Response
     */
    200: AsistenciaListResponse;
};

export type ListAttendanceForAlumnoApiV1AttendanceAlumnoAlumnoIdGetResponse = ListAttendanceForAlumnoApiV1AttendanceAlumnoAlumnoIdGetResponses[keyof ListAttendanceForAlumnoApiV1AttendanceAlumnoAlumnoIdGetResponses];

export type ListObservacionesApiV1PedagogiaObservacionesAlumnoIdGetData = {
    body?: never;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query?: never;
    url: '/api/v1/pedagogia/observaciones/{alumno_id}';
};

export type ListObservacionesApiV1PedagogiaObservacionesAlumnoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListObservacionesApiV1PedagogiaObservacionesAlumnoIdGetError = ListObservacionesApiV1PedagogiaObservacionesAlumnoIdGetErrors[keyof ListObservacionesApiV1PedagogiaObservacionesAlumnoIdGetErrors];

export type ListObservacionesApiV1PedagogiaObservacionesAlumnoIdGetResponses = {
    /**
     * Response List Observaciones Api V1 Pedagogia Observaciones  Alumno Id  Get
     *
     * Successful Response
     */
    200: Array<ObservacionOut>;
};

export type ListObservacionesApiV1PedagogiaObservacionesAlumnoIdGetResponse = ListObservacionesApiV1PedagogiaObservacionesAlumnoIdGetResponses[keyof ListObservacionesApiV1PedagogiaObservacionesAlumnoIdGetResponses];

export type CreateObservacionApiV1PedagogiaObservacionesPostData = {
    body: ObservacionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/pedagogia/observaciones';
};

export type CreateObservacionApiV1PedagogiaObservacionesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateObservacionApiV1PedagogiaObservacionesPostError = CreateObservacionApiV1PedagogiaObservacionesPostErrors[keyof CreateObservacionApiV1PedagogiaObservacionesPostErrors];

export type CreateObservacionApiV1PedagogiaObservacionesPostResponses = {
    /**
     * Successful Response
     */
    201: ObservacionOut;
};

export type CreateObservacionApiV1PedagogiaObservacionesPostResponse = CreateObservacionApiV1PedagogiaObservacionesPostResponses[keyof CreateObservacionApiV1PedagogiaObservacionesPostResponses];

export type GenerateInformeApiV1PedagogiaInformesPostData = {
    body: InformeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/pedagogia/informes';
};

export type GenerateInformeApiV1PedagogiaInformesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateInformeApiV1PedagogiaInformesPostError = GenerateInformeApiV1PedagogiaInformesPostErrors[keyof GenerateInformeApiV1PedagogiaInformesPostErrors];

export type GenerateInformeApiV1PedagogiaInformesPostResponses = {
    /**
     * Successful Response
     */
    201: InformeOut;
};

export type GenerateInformeApiV1PedagogiaInformesPostResponse = GenerateInformeApiV1PedagogiaInformesPostResponses[keyof GenerateInformeApiV1PedagogiaInformesPostResponses];

export type ListInformesApiV1PedagogiaInformesAlumnoIdGetData = {
    body?: never;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query?: never;
    url: '/api/v1/pedagogia/informes/{alumno_id}';
};

export type ListInformesApiV1PedagogiaInformesAlumnoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListInformesApiV1PedagogiaInformesAlumnoIdGetError = ListInformesApiV1PedagogiaInformesAlumnoIdGetErrors[keyof ListInformesApiV1PedagogiaInformesAlumnoIdGetErrors];

export type ListInformesApiV1PedagogiaInformesAlumnoIdGetResponses = {
    /**
     * Response List Informes Api V1 Pedagogia Informes  Alumno Id  Get
     *
     * Successful Response
     */
    200: Array<InformeOut>;
};

export type ListInformesApiV1PedagogiaInformesAlumnoIdGetResponse = ListInformesApiV1PedagogiaInformesAlumnoIdGetResponses[keyof ListInformesApiV1PedagogiaInformesAlumnoIdGetResponses];

export type UploadFotoApiV1PedagogiaFotosPostData = {
    body: FotoCreate;
    path?: never;
    query?: never;
    url: '/api/v1/pedagogia/fotos';
};

export type UploadFotoApiV1PedagogiaFotosPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFotoApiV1PedagogiaFotosPostError = UploadFotoApiV1PedagogiaFotosPostErrors[keyof UploadFotoApiV1PedagogiaFotosPostErrors];

export type UploadFotoApiV1PedagogiaFotosPostResponses = {
    /**
     * Successful Response
     */
    201: FotoOut;
};

export type UploadFotoApiV1PedagogiaFotosPostResponse = UploadFotoApiV1PedagogiaFotosPostResponses[keyof UploadFotoApiV1PedagogiaFotosPostResponses];

export type ListFotosApiV1PedagogiaFotosAlumnoIdGetData = {
    body?: never;
    path: {
        /**
         * Alumno Id
         */
        alumno_id: string;
    };
    query: {
        /**
         * Desde
         *
         * Start date (inclusive)
         */
        desde: string;
        /**
         * Hasta
         *
         * End date (inclusive)
         */
        hasta: string;
    };
    url: '/api/v1/pedagogia/fotos/{alumno_id}';
};

export type ListFotosApiV1PedagogiaFotosAlumnoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFotosApiV1PedagogiaFotosAlumnoIdGetError = ListFotosApiV1PedagogiaFotosAlumnoIdGetErrors[keyof ListFotosApiV1PedagogiaFotosAlumnoIdGetErrors];

export type ListFotosApiV1PedagogiaFotosAlumnoIdGetResponses = {
    /**
     * Response List Fotos Api V1 Pedagogia Fotos  Alumno Id  Get
     *
     * Successful Response
     */
    200: Array<FotoOut>;
};

export type ListFotosApiV1PedagogiaFotosAlumnoIdGetResponse = ListFotosApiV1PedagogiaFotosAlumnoIdGetResponses[keyof ListFotosApiV1PedagogiaFotosAlumnoIdGetResponses];

export type GetNpsSummaryApiV1PedagogiaNpsSummaryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pedagogia/nps/summary';
};

export type GetNpsSummaryApiV1PedagogiaNpsSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: NpsSummary;
};

export type GetNpsSummaryApiV1PedagogiaNpsSummaryGetResponse = GetNpsSummaryApiV1PedagogiaNpsSummaryGetResponses[keyof GetNpsSummaryApiV1PedagogiaNpsSummaryGetResponses];
